language: java
script: mvn clean test cobertura:cobertura jacoco:report coveralls:report
notifications:
  slack:
    on_success: always
    on_failure: always
  email:
    - airlink@gmail.com
    - btao.cn@gmail.com

jdk:
  - oraclejdk8

